services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - db_data:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
